/**
 * Administration → API Documentation.
 * Documentation is generated by the server from the registered route table (GET /api/admin/api-docs),
 * so new endpoints appear automatically. Includes a Swagger-like API Explorer to try calls with the
 * current session token and inspect responses. Explorer calls are tagged "[API Explorer]" in the audit log.
 */
import { useEffect, useMemo, useState } from 'react';
import { BookOpen, Play, Copy, Search, Lock, ArrowDownToLine, ArrowUpFromLine, Server } from 'lucide-react';
import { useFetch } from '../hooks/useFetch';
import { apiRaw } from '../lib/api';
import { useAuth } from '../store/authStore';
import { toast } from '../store/toastStore';
import { PageHeader, Card, PageLoader, ErrorState, Badge, Spinner, EmptyState, Tabs } from '../components/ui';

const METHOD_TONE = { GET: 'bg-emerald-100 text-emerald-700', POST: 'bg-brand-100 text-brand-700', PUT: 'bg-amber-100 text-amber-700', DELETE: 'bg-red-100 text-red-700' };
const pretty = (v) => (typeof v === 'string' ? v : JSON.stringify(v, null, 2));
function Method({ m, className = '' }) { return <span className={`inline-block w-16 text-center rounded px-1.5 py-0.5 text-[11px] font-bold ${METHOD_TONE[m]} ${className}`}>{m}</span>; }
function Code({ value, className = '' }) { return <pre className={`bg-slate-900 text-slate-100 text-xs rounded-lg p-3 overflow-auto max-h-80 ${className}`}>{pretty(value)}</pre>; }

export default function ApiDocs() {
    const { data, loading, error, reload } = useFetch('/admin/api-docs');
    const [dir, setDir] = useState('All');
    const [q, setQ] = useState('');
    const [selId, setSelId] = useState(null);

    const list = useMemo(() => (data?.endpoints || []).filter((e) => (dir === 'All' || e.direction === dir)
        && (!q || `${e.method} ${e.path} ${e.group} ${e.purpose}`.toLowerCase().includes(q.toLowerCase()))), [data, dir, q]);
    const groups = useMemo(() => list.reduce((m, e) => ((m[e.group] ||= []).push(e), m), {}), [list]);
    const sel = data?.endpoints.find((e) => e.id === selId) || list[0];

    if (loading && !data) return <PageLoader label="Generating API documentation…" />;
    if (error) return <ErrorState message={error} onRetry={reload} />;
    const counts = { Core: 0, Inbound: 0, Outbound: 0 };
    data.endpoints.forEach((e) => counts[e.direction]++);

    return (
        <>
            <PageHeader title="API Documentation" subtitle={`${data.title} v${data.version} · ${data.total} endpoints generated from the registered API routes`}
                actions={<button className="btn-secondary" onClick={() => { navigator.clipboard?.writeText(JSON.stringify(data, null, 2)); toast.success('OpenAPI-style JSON copied'); }}><Copy className="h-4 w-4" />Copy JSON</button>} />
            <div className="grid sm:grid-cols-3 gap-3 mb-4 text-sm">
                <div className="card p-3 flex items-center gap-2"><Server className="h-4 w-4 text-brand-600" />Core APIs <b className="ml-auto">{counts.Core}</b></div>
                <div className="card p-3 flex items-center gap-2"><ArrowDownToLine className="h-4 w-4 text-brand-600" />Inbound integration APIs <b className="ml-auto">{counts.Inbound}</b></div>
                <div className="card p-3 flex items-center gap-2"><ArrowUpFromLine className="h-4 w-4 text-brand-600" />Outbound integration APIs <b className="ml-auto">{counts.Outbound}</b></div>
            </div>
            <div className="card p-3 mb-4 text-xs text-slate-600 space-y-1">
                <p><b>Base URL:</b> <code>{window.location.origin}{data.baseUrl}</code> · <b>Auth:</b> {data.authentication}</p>
                <p><b>Errors:</b> <code>{JSON.stringify(data.errorFormat)}</code> · <b>Status codes:</b> {Object.entries(data.statusCodes).map(([k, v]) => `${k} ${v}`).join(' · ')}</p>
            </div>
            <Tabs value={dir} onChange={setDir} tabs={[{ value: 'All', label: 'All', count: data.total }, { value: 'Core', label: 'Core', count: counts.Core }, { value: 'Inbound', label: 'Inbound', count: counts.Inbound }, { value: 'Outbound', label: 'Outbound', count: counts.Outbound }]} />
            <div className="grid lg:grid-cols-[360px_1fr] gap-4 items-start">
                <div className="card overflow-hidden lg:sticky lg:top-20">
                    <div className="p-3 border-b relative"><Search className="h-4 w-4 text-slate-400 absolute left-6 top-1/2 -translate-y-1/2" /><input className="input pl-9" placeholder="Filter endpoints…" value={q} onChange={(e) => setQ(e.target.value)} /></div>
                    <div className="max-h-[70vh] overflow-y-auto">
                        {Object.entries(groups).map(([g, eps]) => (
                            <div key={g}>
                                <p className="px-3 pt-3 pb-1 text-[11px] font-semibold uppercase tracking-wide text-slate-500">{g}</p>
                                {eps.map((e) => (
                                    <button key={e.id} onClick={() => setSelId(e.id)} className={`w-full text-left px-3 py-2 flex items-center gap-2 text-xs hover:bg-brand-50 ${sel?.id === e.id ? 'bg-brand-50 border-l-2 border-brand-600' : ''}`}>
                                        <Method m={e.method} /><span className="font-mono truncate">{e.path.replace('/api/', '')}</span>
                                    </button>))}
                            </div>))}
                        {!list.length && <EmptyState icon={BookOpen} title="No endpoints match" />}
                    </div>
                </div>
                {sel ? <EndpointDetail key={sel.id} ep={sel} /> : <EmptyState icon={BookOpen} title="Select an endpoint" />}
            </div>
        </>
    );
}

function EndpointDetail({ ep }) {
    return (
        <div className="space-y-4 min-w-0">
            <Card>
                <div className="flex flex-wrap items-center gap-2 mb-2"><Method m={ep.method} /><code className="font-mono text-sm font-semibold break-all">{ep.path}</code>
                    <Badge tone={ep.direction === 'Core' ? 'blue' : ep.direction === 'Inbound' ? 'purple' : 'green'}>{ep.direction}</Badge>
                    {!ep.documented && <Badge tone="gray">auto-generated</Badge>}</div>
                <p className="text-sm text-slate-700">{ep.purpose}</p>
                <p className="text-xs text-slate-500 mt-2 flex items-center gap-1"><Lock className="h-3 w-3" />Roles: {ep.roles.join(', ')}</p>
            </Card>
            <div className="grid xl:grid-cols-2 gap-4">
                <Card title="Request payload"><Code value={ep.request} /></Card>
                <Card title="Response payload"><Code value={ep.response} /></Card>
            </div>
            <Card title="Validation rules">
                {ep.rules.length ? <ul className="list-disc pl-5 text-sm text-slate-700 space-y-1">{ep.rules.map((r) => <li key={r}>{r}</li>)}</ul> : <p className="text-sm text-slate-500">No additional rules.</p>}
            </Card>
            <div className="grid xl:grid-cols-2 gap-4">
                <Card title="Example request"><Code value={ep.exampleRequest && Object.keys(ep.exampleRequest).length ? ep.exampleRequest : `${ep.method} ${ep.path}`} /></Card>
                <Card title="Example response"><Code value={ep.exampleResponse || { note: 'Run "Try it" to see a live response' }} /></Card>
            </div>
            <TryIt ep={ep} />
        </div>
    );
}

function TryIt({ ep }) {
    const token = useAuth((s) => s.token);
    const ex = ep.exampleRequest || {};
    const [params, setParams] = useState(Object.fromEntries(ep.params.map((p) => [p, ex.params?.[p] || ''])));
    const [query, setQuery] = useState(ex.query ? JSON.stringify(ex.query, null, 2) : '{}');
    const [body, setBody] = useState(ex.body ? JSON.stringify(ex.body, null, 2) : ep.method === 'GET' || ep.method === 'DELETE' ? '' : '{}');
    const [res, setRes] = useState(null);
    const [busy, setBusy] = useState(false);
    useEffect(() => setRes(null), [ep.id]);
    const unsafe = ep.method !== 'GET';

    const build = () => {
        let path = ep.path.replace(/^\/api/, '');
        for (const p of ep.params) path = path.replace(`:${p}`, encodeURIComponent(params[p] || `:${p}`));
        let qp = {};
        try { qp = query.trim() ? JSON.parse(query) : {}; } catch { throw new Error('Query must be valid JSON'); }
        return { path, qp };
    };
    const send = async () => {
        let b;
        try {
            const { path, qp } = build();
            if (body.trim() && unsafe) { try { JSON.parse(body); } catch { throw new Error('Body must be valid JSON'); } }
            b = { path, qp };
        } catch (e) { toast.error(e.message); return; }
        if (ep.params.some((p) => !params[p])) { toast.error(`Fill in path parameter(s): ${ep.params.join(', ')}`); return; }
        setBusy(true);
        setRes(await apiRaw(b.path, { method: ep.method, params: b.qp, rawBody: unsafe && body.trim() ? body : undefined }));
        setBusy(false);
    };
    const curl = () => {
        try {
            const { path, qp } = build();
            const qs = new URLSearchParams(qp).toString();
            const cmd = `curl -X ${ep.method} "${window.location.origin}/api${path}${qs ? '?' + qs : ''}" \\\n  -H "Authorization: Bearer ${token ? token.slice(0, 12) + '…' : '<token>'}" \\\n  -H "Content-Type: application/json"${unsafe && body.trim() ? ` \\\n  -d '${body.replace(/\s*\n\s*/g, ' ')}'` : ''}`;
            navigator.clipboard?.writeText(cmd); toast.success('cURL copied (token truncated)');
        } catch (e) { toast.error(e.message); }
    };

    return (
        <Card title="Try it – API Explorer" actions={<div className="flex gap-2"><button className="btn-secondary btn-sm" onClick={curl}><Copy className="h-3.5 w-3.5" />cURL</button>
            <button className="btn-primary btn-sm" onClick={send} disabled={busy}>{busy ? <Spinner className="h-3.5 w-3.5 text-white" /> : <Play className="h-3.5 w-3.5" />}Send request</button></div>}>
            {unsafe && <p className="mb-3 text-xs rounded-lg bg-amber-50 border border-amber-200 text-amber-800 p-2">This is a {ep.method} call and will change live data (and be written to the audit log). Use "Reset demo data" to restore the KP demo if needed.</p>}
            <div className="grid xl:grid-cols-2 gap-4">
                <div className="space-y-3">
                    {ep.params.length > 0 && <div><label className="label">Path parameters</label>
                        {ep.params.map((p) => <div key={p} className="flex items-center gap-2 mb-2"><code className="text-xs w-16">:{p}</code><input className="input font-mono text-xs" value={params[p]} onChange={(e) => setParams({ ...params, [p]: e.target.value })} placeholder={p} /></div>)}</div>}
                    <div><label className="label">Query parameters (JSON)</label><textarea className="input font-mono text-xs" rows={4} value={query} onChange={(e) => setQuery(e.target.value)} /></div>
                    {unsafe && <div><label className="label">Request body (JSON)</label><textarea className="input font-mono text-xs" rows={10} value={body} onChange={(e) => setBody(e.target.value)} /></div>}
                </div>
                <div>
                    <label className="label">Response</label>
                    {res ? (
                        <>
                            <div className="flex items-center gap-2 mb-2 text-sm">
                                <Badge tone={res.ok ? 'green' : res.status >= 500 || res.status === 0 ? 'red' : 'yellow'}>{res.status || 'ERR'}</Badge>
                                <span className="text-slate-500">{res.ms} ms</span>
                                {Array.isArray(res.data?.items) && <span className="text-slate-500">{res.data.items.length} items</span>}
                                {Array.isArray(res.data?.records) && <span className="text-slate-500">{res.data.records.length} records</span>}
                                {Array.isArray(res.data) && <span className="text-slate-500">{res.data.length} rows</span>}
                            </div>
                            <Code value={res.data} className="max-h-[480px]" />
                        </>
                    ) : <div className="rounded-lg border border-dashed border-slate-300 p-8 text-center text-sm text-slate-400">Send a request to see the live response.</div>}
                </div>
            </div>
        </Card>
    );
}
